version: '3.8'

services:
  serviceplanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serviceplanner-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVICEPLANNER_DB_PATH=/app/data/serviceplanner.db
    volumes:
      - serviceplanner-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  serviceplanner-data:
    driver: local
