name: Trigger auto deployment for serviceplanner

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/serviceplanner-AutoDeployTrigger-4d5207ec-d5cf-43e6-8458-fb5dac3aee91.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SERVICEPLANNER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SERVICEPLANNER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SERVICEPLANNER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.SERVICEPLANNER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERVICEPLANNER_REGISTRY_PASSWORD }}
          containerAppName: serviceplanner
          resourceGroup: ServicePlanner-RG
          imageToBuild: highphilosopher/serviceplanner:${{ github.sha }}


